### ISSUE TITLE
Error:Cause: peer not authenticated

### ISSUE THREAD

**Issue by Dragon-Boat** [shrikanthkr/Mediaplayer#5]
Error:Cause: peer not authenticated
why?

**Comment by shrikanthkr** [comment]
Can you please provide brief steps.

**Comment by shrikanthkr** [comment]
Also please check your proxy settings, if you are behind a proxy.

**Comment by Dragon-Boat** [comment]
actually,i just download this project, unzip, import to AS and Run. The gradle prompted "peer not authenticated". 
I didn't use any proxy.

**Comment by Dragon-Boat** [comment]
i have solved this problem by using vpn,  maybe caused by  the internet access limit in china.

**Comment by shrikanthkr** [comment]
Yeah. Thanks!
