### ISSUE TITLE
AndroidManifext.xml can't find.

### ISSUE THREAD

**Issue by Dragon-Boat** [shrikanthkr/Mediaplayer#6]
Error:\Mediaplayer-master\swipeadapter\src\main\AndroidManifest.xml can't find.

**Comment by shrikanthkr** [comment]
Swipe adapter is an external library included. Did your grade build completed successfully?

**Comment by shrikanthkr** [comment]
Please pull and try it again.

**Comment by shrikanthkr** [comment]
@Dragon-Boat did that work ??
